name: Build

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build
        run: mvn clean install

